### ISSUE TITLE
Can I increase the font size?

### ISSUE THREAD

**Issue by Lingyun-Mira** [shuding/nextra#1047]
## **1. Is it possible to change the root font size manually using custom CSS like this or is there another way to do this?**

![image](https://user-images.githubusercontent.com/84528271/206505857-9660bb8c-db7a-45d0-9f06-b5823615a973.png)

## **2. How can I implement an additional font option like this in nextra?**

![image](https://user-images.githubusercontent.com/84528271/206506203-ebedc547-a653-4318-8424-0181b72e458c.png)

**Comment by mrmaglet** [comment]
You could simply edit `style/globals.css` like so: 

```css
html {
  font-size: 24px !important;
  font-family: 'Times New Roman', Times, serif !important;
}
```

If you'd want more control you might want to [make a custom theme](https://nextra.site/docs/custom-theme).
