### ISSUE TITLE
Code not highlighted after deploying to GitLab Pages

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#140]
Hi,

I am building a docs site using Nextra, and deploy with GitLab Pages.

When running locally, code are highlighted correctly.

![image](https://user-images.githubusercontent.com/17229109/115994959-cd0d8b00-a60b-11eb-9420-824e4b2346af.png)

However, after deploying to GitLab, it no longer works.

![image](https://user-images.githubusercontent.com/17229109/115994967-dac31080-a60b-11eb-95a5-78ffe71ba514.png)

Here's my [repo](https://gitlab.com/YikSanChan/docs) and here's the GitLab pages https://yiksanchan.gitlab.io/docs/code-not-highlighted.

My guess: I use `.gitlab-ci.yaml` to configure the deployment. That's the only place where I guess may cause a difference between running locally vs. in production. Here's the yaml file https://gitlab.com/YikSanChan/docs/-/blob/master/.gitlab-ci.yml

```yaml
image: node

before_script:
  - npm install --legacy-peer-deps

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  script:
    - npm run-script build && npm run-script export
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - master
```

 Any help? Thanks!
