### ISSUE TITLE
Disable preflight

### ISSUE THREAD

**Issue by nihgwu** [shuding/nextra#1403]
Continue as part of https://github.com/shuding/nextra/issues/747

> Style isolation. My website is for Design System, so it's crucial that the style should not be affected by the external resources.
a. The whole app should add isolation: isolate so the header and sidebar want overlay the modals from user space
b. Try to avoid using preflight, and try to not using atomic classnames, as it will clash with user space style if they are using tailwind in their components with another config

Can we at least disable preflight of TailwindCSS?

**Comment by B2o5T** [comment]
It will be breaking for all users, you should disable preflight on your side since nextra already uses it, also all nextra tailwind class names were prefixed with `nx-` so you should no longer have conflicts with nextra classes

**Comment by B2o5T** [comment]
@shuding I was thinking to bundle preflight styles as a separate CSS file and add a new option in Nextra config to import or not it in our loader

**Comment by nihgwu** [comment]
Preflight is definitely an issue, that if we have a plain `button` element on the page, it will be displayed like a plain text instead of a button, can we use normalise.css or reset.css instead

**Comment by nihgwu** [comment]
@B2o5T if you can disable it by an option it means you don’t need preflight, tbh I don’t think it’s hard to do it, eg. we can apply it to component has data-nectar or had className starts with nx which we don’t need huge change at all

**Comment by B2o5T** [comment]
what's toxic? all styles are reset to looks the same in all browsers

**Comment by nihgwu** [comment]
I think normalise is fine, but reset to nothing than plain text is not

**Comment by nihgwu** [comment]
OK I found preflight is probably fine although we should avoid reseting button/input style, but some of Nextra style is leaked to global

**Comment by nihgwu** [comment]
Right now the biggest problem for me is focus ring pollution and I have to use the following workaround:

```css
#__next {
  isolation: isolate;
  z-index: 0;
}

.nextra-sidebar-container {
  isolation: isolate;
  z-index: 15;
}

a:focus-visible,
summary:focus-visible,
button:focus-visible,
input:focus-visible,
[tabindex]:not([tabindex='-1']):focus-visible {
  box-shadow: none;
}

a[class*='nx-']:focus-visible,
summary[class*='nx-']:focus-visible,
button[class*='nx-']:focus-visible,
input[class*='nx-']:focus-visible,
[tabindex][class*='nx-']:not([tabindex='-1']):focus-visible {
  box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow),
    var(--tw-shadow, 0 0 transparent);
}
```

**Comment by equinusocio** [comment]
I have the same issue using nextra for DS documentation. The main problem is caused by useless CSS resets mainly.

Our DS relies on CSS layers to facilitate consumer overrides, but this means every style coming from the theme, including basic reset (type selectors etc) will override any external style cause they are not inside any named layer.

Probably putting all the CSS coming from nextra inside a named CSS layer may solve the issue, but the user's styles should be imported inside a layer, after the nextra one.

**Comment by ramozdev** [comment]
I am having the same issue, where the TailwindCSS Preflight is behaving in unexpected ways. 

If I create a `<button>` and add the `type="button"` attribute, the background color of the button is set to `transparent` by the [TailwindCSS Preflight](https://unpkg.com/tailwindcss@3.3.1/src/css/preflight.css). This is not the case if I use the `button` tag directly.

### Without `type="button"`

```html copy
<button className="bg-blue-700 text-white p-4">Button</button>
```

### With `type="button"`

```html copy
<button type="button" className="bg-blue-700 text-white p-4">Button</button>
```

Inspect the button with `type="button"` in your browser to see the preflight CSS applied with a higher specificity than the TailwindCSS classes.

```css copy
button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button;
  background-color: transparent;
  background-image: none;
}
```

See this [live example](https://nextra-issue.vercel.app/) where I present the problem. I published the [source code](https://github.com/ramozdev/nextra-issue) which is just the `nextra-theme-docs` modified to create the example.
