### ISSUE TITLE
Support YAML for _meta

### ISSUE THREAD

**Issue by nathanclevenger** [shuding/nextra#1678]
I absolutely love Nextra, but one of the most annoying aspects is dealing with `_meta.json` as unlike MDX, JSON is much less user friendly for rapid editing and changes. This is especially important with folks on the team that are less technical and are comfortable with editing Markdown and MDX, but can get frustrated with editing JSON to the the TOC structure working in Nextra.

I would propose that `_meta.yaml` be supported in addition to `_meta.json` as it would be much more user friendly:

```yaml
index: Introduction
another: Another Page
advanced: Advanced (A Folder)
about:
  title: About
  type: page
contact:
  title: Contact ↗
  type: page
  href: https://twitter.com/shuding_
  newWindow: true
```
