### ISSUE TITLE
Search input is wrongly styled in dark mode

### ISSUE THREAD

**Issue by shuding** [shuding/nextra#17]

**Comment by 0xdhrv** [comment]
I tried some CSS fix using basic inspection of the `nextra-theme-docs/style.css`, and apparently it seems to work for both dark and light modes, however, I am not aware of the core colors used, so I used shades of gray.

**Dark Mode**
![image](https://user-images.githubusercontent.com/19857414/100975900-bd11e380-3564-11eb-8236-b383701f2f5a.png)

**Light Mode**
![image](https://user-images.githubusercontent.com/19857414/100975801-95bb1680-3564-11eb-8402-a1030eb9d19c.png)

**Code**
```css
[type='search'] {
    -webkit-appearance: textfield;
    /* 1 */
    outline-offset: -2px;
    background-color: #FFF;
    border-color: #969696;
    /* 2 */
}

.dark [type='search'] {
    -webkit-appearance: textfield;
    /* 1 */
    outline-offset: -2px;
    background-color: #000;
    border-color: #424242;
    /* 2 */
}

::placeholder {
    /* Chrome, Firefox, Opera, Safari 10.1+ */
    color: #969696 !important;
    opacity: 1;
    /* Firefox */
}

:-ms-input-placeholder {
    /* Internet Explorer 10-11 */
    color: #969696 !important;
}

::-ms-input-placeholder {
    /* Microsoft Edge */
    color: #969696 !important;
}


.dark ::placeholder {
    /* Chrome, Firefox, Opera, Safari 10.1+ */
    color: #424242 !important;
    opacity: 1;
    /* Firefox */
}

.dark :-ms-input-placeholder {
    /* Internet Explorer 10-11 */
    color: #424242 !important;
}

.dark ::-ms-input-placeholder {
    /* Microsoft Edge */
    color: #424242 !important;
}
```
