### ISSUE TITLE
Docs theme `box-decoration-theme: clone` can create confusing output over line breaks

### ISSUE THREAD

**Issue by robations** [shuding/nextra#2129]
The `styles.css` for the docs is adding this style:

```css
code {
    -webkit-box-decoration-theme: clone;
    box-decoration-theme: clone;
}
```

This causes long code blocks to look like separate code blocks when wrapped over a line break (by adding rounded corners to both split elements). `slice` rather than `clone` might be a better default for technical documentation.

I don't see this within the project, so this might be imported from Tailwind.

A picture === 1k words, so here's an ASCII representation:

### Actual (with clone):

```
The file should be named (long-file-name)
(2023-05-01.json)
```

### Expected (with slice):

```
The file should be named (long-file-name]
[2023-05-01.json)
```
