### ISSUE TITLE
Looking to migrate away from DOCFX, but nextra is missing a key feature

### ISSUE THREAD

**Issue by Thraka** [shuding/nextra#2291]
docfx is a pretty good static site generation for developer docs. I use it wat work all the time and I use it in my personal code project, with a retro computer theme: https://sadconsole.com/v9/articles/

However, docfx as a platform has been in limbo for years. I'm looking for a new doc generation system with nice features and nextra seems to fit, except for one thing, API reference links. A powerful part of docfx is that it can scan a .NET DLL and generate API documentation, not only that, it can create an xrefmap file that can be queried to find the link to an API doc based on the API name.

Is there anything in nextra for API docs? It seems to be a big industry gap, closing the whole API + conceptual doc loop. If nextra doesn't have it, does anyone know of a doc solution that does? Thanks!

**Comment by B2o5T** [comment]
it depends on the used language. For javascript/typescript you can generate your API docs (markdown files) with typedoc

**Comment by Thraka** [comment]
These would be non web APIs

**Comment by Thraka** [comment]
I could potentially use docfx to build out the API docs, I just need a convenient way to transform API links into them. In docfx you can configure the locations of xrefmap files which have definitions to translate an API id to a doc link. For example:
```yaml
### YamlMime:XRefMap
sorted: true
references:
- uid: SadConsole.AnimatedScreenObject.AnimationStateChangedEventArgs.#ctor*
  name: AnimationStateChangedEventArgs
  href: api/sadconsole/SadConsole.AnimatedScreenObject.AnimationStateChangedEventArgs.html#SadConsole_AnimatedScreenObject_AnimationStateChangedEventArgs__ctor_
  commentId: Overload:SadConsole.AnimatedScreenObject.AnimationStateChangedEventArgs.#ctor
  name.vb: New
  fullName: SadConsole.AnimatedScreenObject.AnimationStateChangedEventArgs.AnimationStateChangedEventArgs
  fullName.vb: SadConsole.AnimatedScreenObject.AnimationStateChangedEventArgs.New
  nameWithType: AnimatedScreenObject.AnimationStateChangedEventArgs.AnimationStateChangedEventArgs
  nameWithType.vb: AnimatedScreenObject.AnimationStateChangedEventArgs.New
- uid: Microsoft.Xna.Framework.Graphics.TextureExtensions
  name: TextureExtensions
  href: api/monogame/Microsoft.Xna.Framework.Graphics.TextureExtensions.html
  commentId: T:Microsoft.Xna.Framework.Graphics.TextureExtensions
  fullName: Microsoft.Xna.Framework.Graphics.TextureExtensions
  nameWithType: TextureExtensions
```

Then during build of the normal conceptual docs, it will pull in the xrefmap from the URLs you configured and translate xref uid values into href values
```markdown
It can be done like this <xref:SadConsole.AnimatedScreenObject.AnimationStateChangedEventArgs.#ctor*?displayProperty=nameWithType>

It can also be used as a normal markdown link [link text](xref:SadConsole.AnimatedScreenObject.AnimationStateChangedEventArgs.#ctor*)
```
