### ISSUE TITLE
Global stylesheet breaks Amplify

### ISSUE THREAD

**Issue by Samrose-Ahmed** [shuding/nextra#2442]
nextra seems to have a global stylesheet that breaks other stylesheets, e.g. when using with Aws amplify authenticator component: this css in nextra, specifically the background-color, breaks the Amplify authenticator sign in UI's:
```css
button,[type=button],[type=reset],[type=submit] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none
}
```

shouldn't the nextra global styles be scoped, or is there a way to customize?
