### ISSUE TITLE
Please add CSS classes to the docs/blog theme so that individual elements may be targeted.

### ISSUE THREAD

**Issue by lacymorrow** [shuding/nextra#2470]
I'm currently using rules like:

```css
	/* Force page to be full width (Flash pages are smaller than the screen) */
	.wrapper > div[dir] > div[class~="nx-max-w-[90rem]"] {
		width: 100%;
	}

	/* Stick footer to bottom of page */
	.wrapper > div[dir] {
		min-height: 100vh;
		display: flex;
		flex-direction: column;
	}

	footer {
		margin-top: auto;
	}
```

It would be great if there were a few more class names scattered around to make styles/customizations easier.
