### ISSUE TITLE
[nextra-theme-blog] Low accessibility score in lighthouse

### ISSUE THREAD

**Issue by numToStr** [shuding/nextra#475]
Thank you for making `nextra`. I am currently migrating my website from Gatsby to Nextra and found the migration to be really easy and fun ❤️

I ran lighthouse after migration and found accessibility score to be little low. There are mainly two issue that is reported by lighthouse:

- [aria-*] attributes do not match their roles (for theme toggle) https://github.com/shuding/nextra/pull/476
- Background and foreground colors do not have a sufficient contrast ratio.

Website: https://num2str.vercel.app
Lighthouse: https://web.dev/measure/?url=https%3A%2F%2Fnum2str.vercel.app (Press `Run Audit` to see the score)

**Setup**

```yaml
next: "^12.1.6"
nextra: "2.0.0-alpha.56"
nextr-theme-blog: "2.0.0-alpha.54"
react: "18.1.0"
```

I would love to hear your thoughts on this issue :)
